feat: add terraform + multipass conf
AshAvalanche/ansible-avalanche-getting-started pull request #34
Opened 2023-07-21 13:19 UTC by Nuttymoon

### Linked issues

- Fixes #33 

### Breaking changes

- Vagrant+VirtualBox removed in favor of Terraform+Multipass

### Additional comments

Because allocating static IPs in Multipass is a pain in the ass (see [How to configure static IPs](https://multipass.run/docs/configure-static-ips)), I decided to template the Ansible `hosts` file with Terraform (`inventories/local/hosts` is now a symlink to `terraform/multipass/hosts.ini` that will be created upon `terraform apply`).

I am using the example SSH key provided at [Configure instance to be managed by Ansible](https://cloudinit.readthedocs.io/en/latest/reference/examples.html#configure-instance-to-be-managed-by-ansible). I think this is acceptable for local environments. If we want a cleaner option, we could leverage the Terraform [tls_private_key provider](https://registry.terraform.io/providers/hashicorp/tls/latest/docs/resources/private_key).

To try this out:
```bash
# Initialize the Terraform project
terraform -chdir=terraform/multipass init
# Create the local instances through Multipass
terraform -chdir=terraform/multipass apply
# Bootstrap the local environment
ansible-playbook ash.avalanche.bootstrap_local_network -i inventories/local
```

2023-07-23 12:27 UTC, leopaul36 requested changes
Getting:

```
fatal: [validator01]: UNREACHABLE! => changed=false
  msg: |-
    Failed to connect to the host via ssh: @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
    @         WARNING: UNPROTECTED PRIVATE KEY FILE!          @
    @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
    Permissions 0640 for './files/multipass/id_rsa' are too open.
    It is required that your private key files are NOT accessible by others.
    This private key will be ignored.
    Load key "./files/multipass/id_rsa": bad permissions
    ansible@10.252.190.144: Permission denied (publickey).
  unreachable: true
```

We should probably commit `files/multipass/id_rsa` with `600` permissions

2023-07-23 12:27 UTC, leopaul36 commented
Works fine otherwise :+1:

2023-07-24 12:47 UTC, Nuttymoon commented
> Getting:
> 
> ```
> fatal: [validator01]: UNREACHABLE! => changed=false
>   msg: |-
>     Failed to connect to the host via ssh: @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
>     @         WARNING: UNPROTECTED PRIVATE KEY FILE!          @
>     @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
>     Permissions 0640 for './files/multipass/id_rsa' are too open.
>     It is required that your private key files are NOT accessible by others.
>     This private key will be ignored.
>     Load key "./files/multipass/id_rsa": bad permissions
>     ansible@10.252.190.144: Permission denied (publickey).
>   unreachable: true
> ```
> 
> We should probably commit `files/multipass/id_rsa` with `600` permissions

We cannot version with other permission than `644` or `755`, see[Git index format docs](https://git-scm.com/docs/index-format):
> 9-bit unix permission. Only 0755 and 0644 are valid for regular files.

I will add a chmod operation in the `setup.sh`.

2023-07-25 13:45 UTC, leopaul36 approved these changes

2023-07-25 13:45 UTC, leopaul36 commented on inventories/local/group_vars/avalanche_nodes.yml
> +  http-allowed-hosts: "*"
Do we really need to override this since query with an empty `Host` header are accepted?

2023-07-25 13:54 UTC, Nuttymoon commented on inventories/local/group_vars/avalanche_nodes.yml
> +  http-allowed-hosts: "*"
If we don't override this, the `Node security` tutorial won't work as the node won't accept incoming connections to `validator01.ash.local`

2023-07-26 12:13 UTC, merged