feat: add a sol files for foundry
AshAvalanche/ansible-avalanche-getting-started pull request #41
Opened 2024-02-13 10:58 UTC by servalD

### Dependencies

- https://github.com/foundry-rs/forge-std
- https://github.com/OpenZeppelin/openzeppelin-contracts.git

To clone in a new ash_token lib folder.

### Changes

- Add .ash_token folder as a foundy workspace which contains an ERC20 contract and its deployment script.

2024-02-13 16:27 UTC, leopaul36 requested changes

2024-02-13 16:27 UTC, leopaul36 commented on ash_token/.gitignore
> +lib/
Instead of this, create and commit an empty `lib` directory so that it already exists when we use it in the tutorial.

2024-02-13 16:27 UTC, leopaul36 commented on ash_token/src/ASHToken.sol
> +    constructor(uint256 initialSupply) ERC20("ASHToken", "AT") {
```suggestion
    constructor(uint256 initialSupply) ERC20("ASHToken", "ASH") {
```

$ASH works better as ticker

2024-02-14 15:28 UTC, servalD commented on ash_token/src/ASHToken.sol
> +    constructor(uint256 initialSupply) ERC20("ASHToken", "AT") {
I wanted the same but the native blockchain coin has the same symbol.. So in the wallet it's quit confusing to see ASH on both labels. No?

2024-02-15 14:37 UTC, leopaul36 commented on ash_token/src/ASHToken.sol
> +    constructor(uint256 initialSupply) ERC20("ASHToken", "AT") {
Good point I did not think about this :+1:

2024-02-15 16:28 UTC, leopaul36 approved these changes

2024-02-16 13:26 UTC, merged